### ISSUE TITLE
Shade configuration causes issues with other shaded applications

### ISSUE THREAD

**Issue by isaki** [dropwizard/logback-throttling-appender#85]
The shade configuration for this library excludes Google's j2objc-annotations from relocations, which causes conflicts when applications that use the shade plugin attempt to include both this library and j2objc-annotations in the uber jar. I'm more than willing to tweak the pom and submit a PR, but I want to understand why this choice was made before I go make any changes.

One possible fix would be to exclude the libraries from the shaded `logback-throttling-appender` jar that are not relocated and allow normal Maven dependency management to pull in the requisite dependencies. Another would be to only include the things in the shaded jar that absolutely need to be shaded, or if there is no pressing reason to shade at all, to simply build a standard, unshaded library instead.

Thanks!

```
[WARNING] j2objc-annotations-1.3.jar, logback-throttling-appender-1.1.2.jar define 1 overlapping classes: 
[WARNING]   - com.google.j2objc.annotations.RetainedWith
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
```

**Comment by joschi** [comment]
@isaki Thanks for reporting!

This is indeed a bug and `com.google.j2objc.*` should've been relocated accordingly.

It will be fixed in `io.dropwizard.logback:logback-throttling-appender:1.1.3` which should be available on Maven Central soon.

**Comment by isaki** [comment]
Awesome, thank you!
